### ISSUE TITLE
Schema files missing after doing a build

### ISSUE THREAD

**Issue by tiagocorreiaalmeida** [Urigo/graphql-modules#1239]
After doing a typescript build of the project I noticed that the *.graphql files are not copied to the output folder, which resolves in the following error when I run the server with node only
**Error: Apollo Server requires either an existing schema, modules or typeDefs**

I believe this is the normal behavior of typescript and I haven't found a way of getting around it, I tried to look trough the other issues and the docs and I couldn't found anything related to it, what's the best way of having the .graphql files copied to the output folder?
My structure is quite similar to this
src/module/**/schema/file.graphql
I could try to write a script to handle the step of copying it, but first decided to understand how do you handle it?

Thanks in advance for all the help, and this probably just be on Stackoverflow not here

**Comment by maapteh** [comment]
Hi, since we also only build our project with tsc these will not be icked up as you make clear. We copy them after building the app. Our scrip argument is:

`"copy:schema": "cd src && find . -name '*.graphql' | xargs tar cvf - | (cd ../dist; tar xfp -)",`

This basically finds all graphql files and move them to the correct folders.

**Comment by tiagocorreiaalmeida** [comment]
Thank you for that 👍
