### ISSUE TITLE
Thoughts about V1

### ISSUE THREAD

**Issue by fenos** [Urigo/graphql-modules#1504]
Firstly thanks a lot for keeping up the development of the package. 
I'm an incredible fan of "The Guild" packages especially **graphql-modules** 

I've been relying on **GraphQL-Modules** `V0.x` in production for over a year and built numerous servers with it.
Recently I've started to play around with `V1` to understand the new concepts and API.

I personally think that **GraphQL modules** is diverging in the wrong direction to solve the issue of composable GraphQL server. let me explain why.

### Encapsulation and Composition

In the previous version, a **Module** was a real representation of a fully, self-independent part of the schema. 

I could really develop my module in isolation, defining:

- What context my module defines, in order to function or to export to other modules.
- Access to request / response lifecycles through the `Session` in case I wanted to do some special request parsing in a specific module or cleanup/error handling.
- strictly define what dependencies it is dependent on so that I can clearly see what I need if I ever decided to extract the module to a different package.

Once I've finished developing my module I could either registering it in the Main application module or use it as a stand-alone app. 

All I knew is that all the behavior for my module to function was well encapsulated. Once I register it and I didn't need to worry about, how do I externally plug the context, or how do I externally plug specific request/response operations that only this module needs to be aware of, etc... The module abstraction allowed me to use the `Open/Closed` principle which is, open for extension but close for modification. Without modifying application logic I could extend my application.

You could argue that having the logic distributed in different modules and not centralized might be more difficult to reason about. But in reality, it's not, because each module is like a stand-alone application and they follow the single responsibility principle. 

With the newer version 1, this encapsulation is way less robust as new modules are starting to rely on application-level logic and configurations. 

### Global dependencies

With version 1 now everything is either global or scoped to the module that defines it. 
I think a better way of handling this was to still allow developers to opt-in for the strict approach.

Whoever wants to use global registration should be allowed to, but personally, I would not opt-in for that because I really find it more intuitive to look at a module and see exactly what dependencies it uses.

### TypesDef are now required

With the version `0.x` I was able to define modules that weren't graphql specific, in the sense that they were used to bind instances to the DI container, allowing me to create a reusable tool-set that could be injected across other modules.

This toolset wasn't defining types necessarily.

With the new version, I must have a `typeDefs` implemented even if my module is meant just to register instances.

### Conclusion

In conclusion, I believe that there are many good aspects with the new the version (such as the config and InjectableTokens).

However, I'm also concerned that those fundamental changes that have been made to ease the strict approach of defining dependencies and easing the encapsulation, will ultimately make the library "simpler" to use and less opinionated, but in return, we've been given the flexibility that we didn't need, as well as a less robust approach to encapsulation and a less strict system. 

All of this should have come as an extra for people that want to build smaller applications.

Please interpret this issue as a feedback and maybe a way to start a conversation to understand if all that I said make sense or not 😄 

I'm very open to a constructive conversation/contribution.

For now, thanks a lot for your time to look at this issue and for developing graphql-modules. 
I wish you all an amazing New Year to come!

**Comment by maapteh** [comment]
Hi, my team is migrated to v1 and actually starting to really like it. Much simpler, which also helps on maintaining it i presume. I will give some comments which can be helpfull for you, maybe not :)

For example you stated: "Access to request / response lifecycles through the Session in case I wanted to do some special request parsing in a specific module or cleanup/error handling."

Actually we used this a lot in pre v1, for setting cookies on responses to getting header information etc etc. We now put this session information on the main context so anyone who needs to have/set something can use it. In the past we had a common module and then everyone was including that common module. And you know what happens with common/generic stuff on the long run ... they get bloated. So after more then a year a lot was common while it shouldn't. Now in v1 our GlobalContext is guarded and reduced to what everyone needs and other stuff is moved to the module context.

```
    const server = new ApolloServer({
        schema,
        context: async ({ req, connection, res }) => {
            const { headers } = req;
            ...SNIP...
            return {
                token,
                memberId,
                locale,
                loginState,
                session: {
                    req,
                    res,
                },
            };
```

Also in pre v1 we noticed we couldnt have really nice directives who needed common context since that context came later when directive was hit. Now with v1 we finally have access on the main global context in the correct order.

Also the context is now more fine grained. In the past for product module we needed delivery information from that module but not in during mutations. Now we build up the exact context something needs. So we see a huge performance optimalisation in this setup while still having control over what you need from where since the module itself still needs to set its dependency on the other modules dataloader for example.

I still have to put benchmarking back in again since im eager to understand what the impact of the resolver hooks for injecting the context is. But so far our new v1 is running in production for some months and i will have to dig into one memory issue i experienced. But very happy with the changes so far.

**Comment by fenos** [comment]
@maapteh that was a good write up, i'd love to have a little chat on discord about this, especially around the ExecutionContext

**Comment by maapteh** [comment]
The Guild's graphql-modules channel is at https://discord.com/channels/625400653321076807/631489837416841253 this week im off, but next week will be there.

**Comment by kamilkisiela** [comment]
Hi, [The Guild](https://the-guild.dev) here. We decided to change core concepts and simplify the API, focus a lot more on Developer Experience and be closer to GraphQL spec and standards.

Through those years of using GraphQL Modules, we noticed a pattern in which GraphQL API was a monolithic application and teams were working within the same monorepo. There was no reusability of modules, only much smaller units like services were reused.

In those cases, encapsulating modules and tighten them up with dependencies felt like a "discomfort" :)
Teams treated that "strictiness" like a thing they need to overcome just to make the GraphQL Modules happy and working.

We also noticed that they don't really build module-only context objects but rather something that is closer to be global. They shared those context objects with other modules.
The reason new GraphQL Modules are not responsible for creating a context is to move the "shared" data to Dependency Injection and compute values on demand, not ahead of resolvers and middlewares. 
In some cases, developers were doing DB and API calls in context building space just so they could use that data later on in DI and resolvers. This is wrong because it blocks the GraphQL Operation execution and in some operations you don't really need that data.

We started with encapsulation, composition and all of that but at the end nobody took advantage of it the way it was designed.

About global dependencies. Right the DI is much more advanced butt also flexible. Each module has its own Injector, the application has one as well. There are two kinds of Injectors, Singleton (app lifetime) and Operation (starts and ends with GraphQL operation).
Before, when someone wanted to use `Logger` he had to import `LoggerModule`. Right now this is defined on Application level and if Logger is missing you get an error that explains everything in details (what is missing, where it's missing etc).
The logic of legacy GraphQL Modules was too complex to maintain and not flexible enough to move forward, that's because of encapsulation.
For example, mocking providers of imported modules was impossible. 
Imagine doing an integration test on an Application (Root GraphQL Module with other modules as dependencies) and you want to mock `DbProvider`. 

You couldn't, now you do:

```javascript
mockApplication(app)
  .replaceModule(
    mockModule(
      DbModule,
      {
        providers: [{ provide: DbProvider, useFactory: mockDbProvider }]
      }
    )
  );
```

What I meant by better Developer Experience? Simplicity, flexibility and tooling. 
- Because we follow GraphQL spec and the standards, IDE extensions will work nicely with the new architecture.
- You gain much nicer GraphQL Codegen support. 
- Official Testkit with a lot of useful utilities.
- Richer error messages with locations of modules (if available)

It's even easier to contribute now and maintain it as well.

The TypeDefs are required because module are designed to define pieces of GraphQL API (schema + resolvers). You can use directories to group providers.

**Comment by kamilkisiela** [comment]
The purpose of `ExecutionContext` is to let Singletons access GraphQL Operation and Operation-scoped things. Something most people won't benefit from but it's there. In my opinion, it's better to not mix Operation and Singletons together and limit that to minimum.

**Comment by maapteh** [comment]
@kamilkisiela do you have then maybe an example for a dataloader which needs the context?

At the moment we are doing:
```
@Injectable({
    scope: Scope.Operation,
})
export class CookDataloader {
    constructor(
        @Inject(CONTEXT) private context: GraphQLModules.GlobalContext,
    ) {}

    private dataLoader = new DataLoader<number, unknown, Cook | null>(
        async keys => {
            const response = await fetch(
                this.context.token,
                `${config.service.cookService}/descriptions?userId=${keys}`,
            );

            const data = await handleResponse<
                CookRaw.CookDescription[]
            >(response);

            return normalizeCookUsers(data, keys);
        },
    );

    load(id: number) {
        return this.dataLoader.load(id);
    }
}
```

**Comment by fenos** [comment]
Thanks a lot for everyone's feedback.
I've now spent quite some time refactoring an existing graphql server to the new version of `graphql-modules`

I just had to give it a deeper go with it, I can see that all your statements @kamilkisiela are absolutely correct.

I still have few questions here and there but I'll reach out in a way or another 😄 

Well done guys.

**Comment by dotansimha** [comment]
Thank you for your feedback @fenos ! Really glad that you are enjoying v1 :) Feel free to reach out if you have any issue!
