### ISSUE TITLE
Will there be Relay support?

### ISSUE THREAD

**Issue by alfaproject** [Urigo/graphql-modules#184]
In my current APIs I have a lot of Relay stuff like the `Node` interface and `node` field, plus connections et al.

I was wondering if you guys thought about it or if you have any tips to implement something like the `node` field, which gets any object in any module by id.

**Comment by dotansimha** [comment]
Hi @alfaproject !
Basically, there it no reason you won't be able to use Relay structure to define your GraphQL schema.

let's say that you have a GraphQL `interface` called `Node`, and there are multiple types that implements it, and you separate it to GraphQL Modules:

```graphql
# Module: common
interface Node {
   id: ID!
}

interface Query {
   node(id: ID!): Node
}

# Module: user
type User implements Node {
   id: ID!
   username: String!
}

# Module: post
type Post implements Node {
   id: ID!
   title: String!
}
```

Modules `user` and `post` depends on `common`. 

Now, the issue here is that `user` depends on `common`. And also `post` depends on `common`, but you don't want `common` to know about the implementing types. So that's makes it a bit difficult to 
find those entities, and then to implement `__resolveType` for this `interface`. 
But there is a solution.
We can assume that you detect which type of entity you are using by a field called `type` on your objects.

You can create a `Provider` in `common` called `NodeTypeResolver`, and do implement a registration mechanism, that keeps a mapping between your internal types and the GraphQL types and a function that tries to fetch the object by it's `id`:

```ts
import { Injectable } from '@graphql-modules/core';

@Injectable()
export class NodeTypeResolver {
   _map: Map<string, { type: string, fetchFn: Function }> = new Map();

   registerType(objectType: string, gqlType: string, fetchFn: Function) {
        this._map.set(objectType, { type: gqlType, fetchFn });
   }

   async getById(id: string) {
       for (const handlers of _map.values()) {
           const value = await handlers.fetchFn(id);
 
           if(value) {
                return value;
            }
       }

       return null;
   }
 
   getGqlType(objectType: string) {
       return this._map.get(objectType).type;
   }
}
```

Now, the `common` module resolver for `Node` and `Query` can be implemented like that:

```ts
export const resolvers = {
    Node: {
        __resolveType: (object, context, info) => context.injector.get(NodeTypeResolver).getGqlType(object.type);
     },
     Query: {
          node: (root, args, context, info) => context.injector.get(NodeTypeResolver).getById(args.id),
      },
} 
``` 

So now when someone asks for `node(id)` with some id:

```graphql
query {
   user: node(id: "1") {
         id
         ... on User {
            username
         }
   } 
   post: node(id: "2") {
         id
         ... on Post {
            title
         }
   } 
}
```

, the resolver of `Query.node` will trigger all registered `fetchFn` and tries to find the object by it's id. If it find it, it returned and resolved using `__resolveType` that matches between the object type and the GraphQL type, and then triggers the correct `type` resolver.

In modules `user` and `post`, you can add a `Provider` that registers the types:

```ts
import { Injectable } from '@graphql-modules/core';

@Injectable()
export class UserProvider {
    constructor(nodeTypeResolver: NodeTypeResolver) {
         nodeTypeResolver.registerType('user', 'User', this.getUserById);
    }

    getUserById(id: string) {
          // Try to find the user by id
    }
}
```

```ts
import { Injectable } from '@graphql-modules/core';

@Injectable()
export class PostProvider {
    constructor(nodeTypeResolver: NodeTypeResolver) {
         nodeTypeResolver.registerType('post', 'Post', this.getPostById);
    }

    getPostById(id: string) {
          // Try to find the post by id
    }
}
```
