### ISSUE TITLE
Querying schema internally?

### ISSUE THREAD

**Issue by dodas** [Urigo/graphql-modules#235]
Hi,
is it possible to query the generated schema internally, i.e. without network / graphql server?
Normally, it is possible to pass schema to `graphql` function and query against it.
See: https://github.com/graphql/graphql-js/issues/1043#issuecomment-333571675

When I try to do the same with graphql-modules, I get `TypeError: Cannot read property 'moduleNameContextMap' of undefined`.

Should this be doable somehow?

I am currently using `@graphql-modules/core` version `0.3.0-alpha.d74cc126`.

Thanks!

**Comment by ardatan** [comment]
Hi dodas,
GraphQL-Modules resolvers use context that is exported from the module, so you cannot use them seperately. We have better error handling to throw more readable error about this case.
There is a `contextValue` field in that function, you can provide a context by using context builder function exported from the module like we use in our tests;
https://github.com/Urigo/graphql-modules/blob/9ce6ba88893893962bb1dd2a2d5b310fd98d4883/packages/core/tests/graphql-module.spec.ts#L137

**Comment by dodas** [comment]
That's what I did: I used both schema and context exported from module.
It seems like my error is coming from here https://github.com/Urigo/graphql-modules/blob/9ce6ba88893893962bb1dd2a2d5b310fd98d4883/packages/core/src/graphql-module.ts#L614
It is missing request that I am not sure where should come from.

**Comment by ardatan** [comment]
Could you share an example how you pass context and schema to `graphql` function?

**Comment by ardatan** [comment]
Closed due to inactivity. Feel free to open it if you have still this issue.

**Comment by bros4president** [comment]
For anyone in the same situation, I found a workaround using the `gql` tag (AST behind the scenes) and `application.createExecution`

Notice that you can use `graphql(schema, query)` with `query` being a string, but you can also use `execute(schema, queryAST)` where `queryAST ` is the AST for `query`.

This:
```javascript
import { graphql } from "graphql";

const query = "{ hello }";
graphql(schema, query);
```

Is roughly* same as this:
```javascript
import { execute} from "graphql";
import { gql } from "graphql-modules";

const query = gql`{ hello }`;
execute(schema, query);
```

Now, for simple queries like that it'll work with `execute` from graphql.js out of the box. But when it comes to variables and context it's not enough so you'll need to create your own `execute` function.

Luckily graphql-modules supports this with `application.createExecution`. Here's the idea:
```javascript
import { createApplication, gql } from "graphql-modules";
import { aModule, bModule } from "./myModules";

const queryAST= gql`{ hello }`

// Create graphql-modules app and app execute function
const app = createApplication({modules: [aModule, bModule]});
const execute = app.createExecution()

execute(app.schema, astQuery)
```

And this is the complete snippet with variables:
```javascript
import { createApplication, gql } from "graphql-modules";
import { aModule, bModule } from "./myModules";

const queryAST= gql`
    mutation SomeMutation($input: someMutationInput!) {
        doSomething(input: $input) {
            someOutputField
            anotherOutputField
        }
    }
`
const variables = {
    input: {
        foo: "bar",
    }
}

// Create graphql-modules app and app execute function
const app = createApplication({modules: [aModule, bModule]});
const execute = app.createExecution()

execute(app.schema, astQuery, undefined, undefined, variables)
```

----------------------------------------------------------------------
* I say roughly because graphql.js's `execute` function it's ultimately called by the `grapqh` function itself, but it also performs checks and other stuff. This worked for my needs, but it may not for yours. I'd recommend checking the definition of the `grapqh` function and see if it suits you :)
