### ISSUE TITLE
Modules are a pain

### ISSUE THREAD

**Issue by orefalo** [Urigo/graphql-modules#244]
So I split my IDL schema in multiple files:
* commons.graphql
* customer.graphql
* catalog.graphql
* order.graphql

of course, there is cross dependency between these files.

Just pointing out that having to manually add # import TaxExemptionEnum from '../commons/commons.graphql'
is REALLY painful. Any idea how to solve this?

**Comment by dotansimha** [comment]
Hi @orefalo ! 
Why do you need to load this enum with `#import`? 
With `epoxy`, you don't have to do it at all, just use the enum, and add a dependency for the commons module in your other modules.

**Comment by orefalo** [comment]
Happy new year,

I didn't know about epoxy but I believe it works under the hood.

Anyways, let me add to the description above, I missed something ;-)

Each module, has its own ild and resolver file.
The IDL itself is loaded via 

```
import "graphql-import-node"
import * as typeDefs from "./catalog.graphql"
```


-> Now this is where the problem happens, **graphql-import-node** will complain when a type is not defined in the current file... that's why I need all these imports.

Am I doing something wrong?
Is there a better way to organize the code?

**Comment by dotansimha** [comment]
Happy new year @orefalo ! 

No need to use `graphql-import-node` in this case.
`graphql-modules` comes with a tool called `epoxy` for merging schemas, and a tool called `sonar` for locating and loading `.graphql` files.

See the following example: https://graphql-modules.com/docs/guides/load-your-schema#using-sonar-and-epoxy

**Comment by orefalo** [comment]
thank you, you made my 2019!
closing issue

**Comment by orefalo** [comment]
actually.. it doesn't solve the issue.
the example works fine because all .graphql are within the same module.

**Comment by dotansimha** [comment]
Ohh I see now. So your `order-module` basically needs `type User` to be there, and that's probably for a reason. 

You can do one of the following:

### Option 1 - Import user module
If there is a direct connection between those modules, then `order-module` should know about the types of `user-module`. You can do that by adding `imports: [userModule]` in your `order-module` declaration. This way, when `graphql-modules` will merge the types of `user-module` and `order-module` while building the schema.

### Option 2 - Stub declaration

If `order-module` has no direct connection to `user-module`, so it should not reference `User` at all, or, if it does need `User` to be there without caring about it's fields, you can declare a stub type `type User { id: ID! }` in this module, because it actually needs it. 
Later, `graphql-modules`  will make sure to merge all declarations of `type User` into a single type with all the fields.

**Comment by orefalo** [comment]
Tks, will try
