### ISSUE TITLE
Ugraded to 0.4 : RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by orefalo** [Urigo/graphql-modules#317]
```
.../graphql/src/modules/order/index.ts:16
  imports: () => [CommonModule, PartyModule, CatalogModule]
           ^
RangeError: Maximum call stack size exceeded
    at Object.imports (.../graphql/src/modules/order/index.ts:16:12)
    at GraphQLModule.get selfImports [as selfImports] (.../graphql/node_modules/@graphql-modules/core/src/graphql-module.ts:589:33)
    at GraphQLModule.buildSchemaWithMakeExecutableSchema (.../graphql/node_modules/@graphql-modules/core/src/graphql-module.ts:262:30)
    at GraphQLModule.buildSchemaWithMakeExecutableSchema (.../graphql/node_modules/@graphql-modules/core/src/graphql-module.ts:266:16)
```

Was working fine before... any idea?

tks

**Comment by orefalo** [comment]
So... my Order module... imports my party module... and vis versa.

I have no idea how to fix it...

**Comment by ardatan** [comment]
Since 0.4.0, Circular dependencies are not supported anymore. If you want to keep them, you can stay at the old version. But otherwise you have to fix circular dependencies.

**Comment by orefalo** [comment]
well.. that's a real concern as far as I am concerned.
closing this issue.

Will most likely strip away modules.

**Comment by Urigo** [comment]
@orefalo this was on purpose because we haven't found a use case where leaving this option would make less good then damage.
If you think otherwise, we would love to see your use case and help.
Also, if it's code that you can't share in the open, we can jump on a call and discuss if it's more comfortable for you.
Looking forward to hear your thoughts

**Comment by orefalo** [comment]
Thank you @Urigo, much appreciated. Let me share the concepts as the code base is getting a little complex by now.

It's very simple: let's take the example above.  Party<->Order
      each domain has its own module.

Domain Order (Module):
```
type Order {
...
# get the list of engaged parties during order capture
# for self served channels, the customer is only party role
engagedParties: [PartyRole!]!
...
}
```

Domain Party (Module)
```
type Party {
...
# list of placed orders
order: [Order]!
...
}

type PartyRole {
...
}
```

So... How to get around the circular dep?

**Option 1**: Move PartyRole to its own module.
   In fact, I am not even sure this will fix it, but regardless I believe this will quickly become unmaintainable. I am close to 15 domains now.
      
**Option 2**: Generalize the types, Use the Node type for instance! or a more generic one...
    Fine... however it kinds of defeat the purpose:
            first I will loose a strongly type schema
            second it's a pain for the client.


Modules are great for full layers like authentication but for a canonical model, it's hard (especially without circular dependencies)

At this point, my conclusions is that modularity is better achieved by creating separate graphql instances (one per domain) and stitching them together.

What do you think?

**Comment by ardatan** [comment]
Let's take another example to make it clear;
We have 3 different entities in your database;
`User`, `Post` and `Comment`
- `User` doesn't depend on `Post` and `Comment`
-`Post` doesn't depend on `Comment`.
But 
- `Comment` depends on `User` and `Post`, because it has `userId` and `postId` fields
- `Post` also depends on `User` because it has `userId` field

So let's create modules in that way,
**UserModule**
```gql
type User {
  id: ID
  name: String
  username: String
  email: String
  ## Some other fields
}
```

**PostModule** imports **UserModule**
```gql
type Post {
  id: ID
  title: String
  content: String
  user: User
}
extend type User {
  posts: [Post]
}
```

**CommentModule** imports both **PostModule** and **UserModule**
```gql
type Comment {
  id: ID
  content: String
  user: User
  post: Post
}
extend type Post {
  comments: [Comment]
}
extend type User {
  comments: [Comment]
}
```

Using this approach, you will have standalone modules; otherwise it will be like a big module contains all of them like we used to handle circular deps in this way.

Also `extend` says that it needs a main definition from imported modules.
On the other hand, you will keep data fetching logic for different types seperate from each other;
you will resolve `Comment` only in `CommentModule`.

You can check this blog post related to this approach;
https://medium.com/the-guild/why-is-true-modular-encapsulation-so-important-in-large-scale-graphql-projects-ed1778b03600

**Comment by orefalo** [comment]
Indeed... at that's an elegant way to solve the issue. thank you for opening my eyes.

**Comment by ardatan** [comment]
I wrote a blog post about it;
https://medium.com/the-guild/manage-circular-imports-hell-with-graphql-modules-4b1611dee781

**Comment by KROSF** [comment]
@ardatan your solution for circular deps is amazing.
how can i do the same with typegraphql?
