### ISSUE TITLE
Exclude root types

### ISSUE THREAD

**Issue by tlivings** [Urigo/graphql-modules#325]
Is it possible to exclude an imported root type (query, mutation, subscription)?

For example, it should be possible for a module `A` to import `B` and reuse its typeDefs without exposing the root types as part of its schema.

Perhaps something along the lines of:

```javascript
export default new GraphQLModule({
  typeDefs,
  resolvers, 
  imports: [ { module: B, exclude: [ 'Query.*'] } ]
});
```

**Comment by ardatan** [comment]
Hi @tlivings,
Yes, it is possible and we don't need any specific option for that;
You can use `forChild` for this stuff.
For example there is a module that exposes different type definitions according to the module's configuration

So when you use `MyModule.forChild({ doNotExpose: true })`
`MyModule` will generate a different schema while it is the same in the rest of the application (edited) 
That's why we have `forChild` and `forRoot`;
```const MyModule = new GraphQLModule({
   typeDefs: ({ config }) => config.doNotExpose ? alwaysExposedTypes : [alwaysExposedTypes, conditionallyExposedTypes]
})```
```const OtherModule = new GraphQLModule({
  imports: [ MyModule.forChild({ doNotExpose: true }) ]
})```
```const FooModule = new GraphQLModule({
  imports: [ MyModule ]
})```
FooModule has `conditionallyExposedTypes` while OtherModule doesn't.

While `forRoot` applies the configuration for all the application, `forChild` only applies it for that module.

**Comment by tlivings** [comment]
Yes but this would require every module have knowledge of when it needs to expose a type vs not.

My question is whether we can, without an imported module’s knowledge, choose what to import and not.

**Comment by ardatan** [comment]
Correct me if I'm wrong, in order to define what to import from a module, I should know what that module has. So, it means indirect manipulation on that standalone module.
Instead of this manipulation, isn't staying inside the child module's boundaries by using configuration better way to prevent possible errors in the future?

**Comment by tlivings** [comment]
Here is the use case: I write a module that builds upon another module, but I don’t want to expose its api surface to users, only my own. This could be for many reasons, but for example: not wanting to expose an api that end users don’t have permission for, etc.

Asking every author to enable a config option for this is not realistic, so having the framework facilitate this in an easy way makes more sense.

**Comment by ardatan** [comment]
Added in 0.7.6!
