### ISSUE TITLE
Possible to pass the context to submodules?

### ISSUE THREAD

**Issue by abhijeet1403** [Urigo/graphql-modules#389]
Is it possible to pass context in submodules from the root module?
Currently only injector is being passed. I want to pass extra objects in the context at the root module which I want to use in all imported modules and submodules.

**Comment by ardatan** [comment]
That violates encapsulation, that's why I recommend to create a common module which creates the context for you as a child module then this context can be shared in other modules.
Check this out;
https://medium.com/the-guild/why-is-true-modular-encapsulation-so-important-in-large-scale-graphql-projects-ed1778b03600
