### ISSUE TITLE
Async Provider Initialization

### ISSUE THREAD

**Issue by travigd** [Urigo/graphql-modules#525]
Is there a way to do initialization of providers that involves asynchronous steps?

I want to do something like connect to the database in the provider and don't want the provider to be accessible before it's fully initialized. It's not that hard to make lazy (just make the `getDB` method memoized and async) but it'd still be nice to have the option to wait for the provider to initialize (especially when providers further down the road depend on it).

**Comment by ardatan** [comment]
We don't have async providers yet, because our DI is sync, not promise-based but you can do something like below;
```ts
@Injectable()
export class DatabaseProvider implements OnInit {
  private _client: SomeClientType;
  async onInit(){
    this._client = await someConnectionLogic();
  }
  getClient(){
    return this._client;
  }
}
```

Let's keep this open until we have proper solution.

**Comment by ardatan** [comment]
The internal logic of DI is sync and I think we must leave this like that because instantation of the classes and constructors are sync in JavaScript.

**Comment by travigd** [comment]
I think this issue to be re-opened.

`onInit` does not need to be sync (it can return a promise). There's currently no way to eager-load providers which means that there's no way to fail fast.

For example, if the database can't be connected to, we should fail on initialization and not when we try to make the first query. There's also no way to throw an error that propagates up so I'm forced to `process.exit(1)` from the provider init method which is not ideal.

**Comment by ardatan** [comment]
If you use promises in onInit, you're right; because injector is created sync(so schema by default like other schema stitching alternatives) , not async. But http requests and context generation is async. That's why, onRequest, onResponse and onConnect etc are async while onInit is sync. You can connect your database outside of GraphQL Modules' DI then pass it using Module Configuration. But if you use something like connection pooling, you can use promises with hooks.
 
However you can also have a workaround like below;

db.provider.ts
```ts
@Injectable()
export class DbProvider {
 
  async init(){
   // db connection logic
 }
}
```

main.ts
```ts
const { schema, injector } = AppModule;

await injector.get(DbProvider).init();

// than bootstrap your application.
```

https://graphql-modules.com/docs/recipes/db-connection-pooling

**Comment by travigd** [comment]
That's true but it definitely feels like something that should be supported in a first-class way, and having to extract out all of the async-init providers at the top level defeats some of the purpose of having separate modules.

**Comment by LucienLee** [comment]
For the reference,  nestjs, one of the popular DI js frameworks, has async provider syntax. That's convenient. https://docs.nestjs.com/fundamentals/async-providers
